import type { ABI } from './types';
export declare const minABI: ABI;
export declare const lpABI: ABI;
export declare const nftABI: ABI;
declare type aaveABIs = 'staking' | 'incentives' | 'lp' | 'lending' | 'uiDataProvider' | 'dataProvider';
export declare const aave: Record<`${aaveABIs}ABI`, ABI>;
declare type balancerABIs = 'token' | 'vault' | 'pool';
export declare const balancer: Record<`${balancerABIs}ABI`, ABI>;
declare type beethovenxABIs = 'masterChef';
export declare const beethovenx: Record<`${beethovenxABIs}ABI`, ABI>;
declare type snowballABIs = 'gauge' | 'farm' | 'staking';
export declare const snowball: Record<`${snowballABIs}ABI`, ABI>;
declare type traderjoeABIs = 'masterChef' | 'bankController' | 'market';
export declare const traderjoe: Record<`${traderjoeABIs}ABI`, ABI>;
declare type pancakeswapABIs = 'registry' | 'autoCakePool';
export declare const pancakeswap: Record<`${pancakeswapABIs}ABI`, ABI>;
declare type lydiaABIs = 'registry' | 'lydFarm' | 'maximusFarm';
export declare const lydia: Record<`${lydiaABIs}ABI`, ABI>;
declare type autofarmABIs = 'registry' | 'pendingRewards';
export declare const autofarm: Record<`${autofarmABIs}ABI`, ABI>;
declare type beltABIs = 'masterBelt' | 'token' | 'staking';
export declare const belt: Record<`${beltABIs}ABI`, ABI>;
declare type alpacaABIs = 'token';
export declare const alpaca: Record<`${alpacaABIs}ABI`, ABI>;
declare type curveABIs = 'provider' | 'registry' | 'cryptoRegistry' | 'factory' | 'poolInfoGetter' | 'gauge' | 'gaugeFactory';
export declare const curve: Record<`${curveABIs}ABI`, ABI>;
declare type bzxABIs = 'token';
export declare const bzx: Record<`${bzxABIs}ABI`, ABI>;
declare type compoundABIs = 'controller' | 'market';
export declare const compound: Record<`${compoundABIs}ABI`, ABI>;
declare type yearnABIs = 'deployer' | 'vault' | 'token';
export declare const yearn: Record<`${yearnABIs}ABI`, ABI>;
declare type venusABIs = 'controller' | 'market' | 'vault' | 'xvsVault';
export declare const venus: Record<`${venusABIs}ABI`, ABI>;
declare type spookyswapABIs = 'masterChef';
export declare const spookyswap: Record<`${spookyswapABIs}ABI`, ABI>;
declare type beefyABIs = 'vault' | 'staking';
export declare const beefy: Record<`${beefyABIs}ABI`, ABI>;
declare type waultABIs = 'master';
export declare const wault: Record<`${waultABIs}ABI`, ABI>;
declare type quickswapABIs = 'registry' | 'dualRegistry' | 'farm' | 'dualFarm' | 'staking';
export declare const quickswap: Record<`${quickswapABIs}ABI`, ABI>;
declare type benqiABIs = 'controller' | 'market';
export declare const benqi: Record<`${benqiABIs}ABI`, ABI>;
declare type axialABIs = 'masterChef' | 'token' | 'swap' | 'gaugeProxy' | 'sAxial' | 'veAxial';
export declare const axial: Record<`${axialABIs}ABI`, ABI>;
declare type mstableABIs = 'asset' | 'vault' | 'staking' | 'mbpt' | 'stable';
export declare const mstable: Record<`${mstableABIs}ABI`, ABI>;
declare type penguinABIs = 'master' | 'nest';
export declare const penguin: Record<`${penguinABIs}ABI`, ABI>;
declare type screamABIs = 'controller' | 'market' | 'staking';
export declare const scream: Record<`${screamABIs}ABI`, ABI>;
declare type cycleABIs = 'distributor' | 'vault' | 'intermediary' | 'staking';
export declare const cycle: Record<`${cycleABIs}ABI`, ABI>;
declare type teddyABIs = 'trove' | 'stabilityPool' | 'staking';
export declare const teddy: Record<`${teddyABIs}ABI`, ABI>;
declare type everestABIs = 'farm' | 'staking';
export declare const everest: Record<`${everestABIs}ABI`, ABI>;
declare type apeswapABIs = 'masterApe' | 'polyMasterApe' | 'rewarder' | 'vaultMaster';
export declare const apeswap: Record<`${apeswapABIs}ABI`, ABI>;
declare type sushiswapABIs = 'masterChef';
export declare const sushiswap: Record<`${sushiswapABIs}ABI`, ABI>;
declare type yieldyakABIs = 'farm' | 'staking';
export declare const yieldyak: Record<`${yieldyakABIs}ABI`, ABI>;
declare type creamABIs = 'controller' | 'token' | 'staking';
export declare const cream: Record<`${creamABIs}ABI`, ABI>;
declare type wonderlandABIs = 'memo';
export declare const wonderland: Record<`${wonderlandABIs}ABI`, ABI>;
declare type boujeABIs = 'masterChef';
export declare const bouje: Record<`${boujeABIs}ABI`, ABI>;
declare type pangolinABIs = 'controller';
export declare const pangolin: Record<`${pangolinABIs}ABI`, ABI>;
declare type avalaunchABIs = 'staking';
export declare const avalaunch: Record<`${avalaunchABIs}ABI`, ABI>;
declare type moonpotABIs = 'pot';
export declare const moonpot: Record<`${moonpotABIs}ABI`, ABI>;
declare type alligatorABIs = 'factory' | 'masterChef';
export declare const alligator: Record<`${alligatorABIs}ABI`, ABI>;
declare type apwineABIs = 'registry' | 'future' | 'staking';
export declare const apwine: Record<`${apwineABIs}ABI`, ABI>;
declare type paraswapABIs = 'staking';
export declare const paraswap: Record<`${paraswapABIs}ABI`, ABI>;
declare type paladinABIs = 'token' | 'pool';
export declare const paladin: Record<`${paladinABIs}ABI`, ABI>;
declare type harvestABIs = 'staking';
export declare const harvest: Record<`${harvestABIs}ABI`, ABI>;
declare type truefiABIs = 'pool';
export declare const truefi: Record<`${truefiABIs}ABI`, ABI>;
declare type platypusABIs = 'staking' | 'masterChef' | 'factoryChef' | 'token';
export declare const platypus: Record<`${platypusABIs}ABI`, ABI>;
declare type lostworldsABIs = 'staking';
export declare const lostworlds: Record<`${lostworldsABIs}ABI`, ABI>;
declare type pikaABIs = 'perpetualV2' | 'vaultFeeV2';
export declare const pika: Record<`${pikaABIs}ABI`, ABI>;
export {};
